#!/usr/bin/env python3
"""Generate components/tz/tz_table.c: IANA timezone name -> POSIX TZ string.

The ESP32 has no timezone database; newlib understands POSIX TZ strings
(e.g. "PST8PDT,M3.2.0,M11.1.0"). TZif v2+ files end with exactly that string,
so we read it from the system zoneinfo (or a given directory).

    python3 tools/gen_tz.py [/usr/share/zoneinfo]
"""
import os
import sys

ZONEINFO = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/zoneinfo"
OUT = os.path.join(os.path.dirname(__file__), "..", "components", "tz", "tz_table.c")


def footer(path):
    data = open(path, "rb").read()
    if not data.startswith(b"TZif") or data[4:5] < b"2":
        return None
    parts = data.rstrip(b"\n").rsplit(b"\n", 1)
    return parts[1].decode() if len(parts) == 2 and parts[1] else None


def canonical_zones():
    names = {"UTC"}
    with open(os.path.join(ZONEINFO, "zone.tab")) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            names.add(line.split("\t")[2].strip())
    return sorted(names)


rows = []
for name in canonical_zones():
    tz = footer(os.path.join(ZONEINFO, name))
    if tz:
        rows.append((name, tz))

with open(OUT, "w") as f:
    f.write("// Generated by tools/gen_tz.py - do not edit.\n")
    f.write("// IANA timezone name -> POSIX TZ string (from TZif footers).\n")
    f.write('#include "tz.h"\n\n')
    f.write("const tz_entry_t TZ_TABLE[] = {\n")
    for name, tz in rows:
        f.write(f'    {{"{name}", "{tz}"}},\n')
    f.write("};\n")
    f.write(f"const int TZ_TABLE_COUNT = {len(rows)};\n")
print(f"wrote {len(rows)} zones to {os.path.normpath(OUT)}")
