#!/usr/bin/env python3
"""Generate tests/host/fixtures/tz_fixture.h: UTC offsets and wall-clock->UTC conversions
computed by Python's zoneinfo (the reference) for zones from components/tz/tz_table.c.
Africa/Casablanca is left out on purpose: its Ramadan changes are listed transitions, not a POSIX rule.
The C TZ engine must reproduce them from the POSIX strings alone."""
import os, re, datetime as dt
from zoneinfo import ZoneInfo

ROOT = os.path.join(os.path.dirname(__file__), "..")
table = dict(re.findall(r'\{"([^"]+)", "([^"]+)"\}', open(os.path.join(ROOT, "components/tz/tz_table.c")).read()))
zones = ["America/Los_Angeles", "America/New_York", "America/St_Johns", "America/Santiago", "America/Sao_Paulo",
         "Europe/London", "Europe/Berlin", "Europe/Dublin", "Africa/Johannesburg", "Asia/Kolkata",
         "Asia/Tehran", "Australia/Sydney", "Australia/Lord_Howe", "Pacific/Auckland", "Pacific/Chatham", "UTC"]
zones = [z for z in zones if z in table]
offsets, conversions = [], []
start = dt.datetime(2026, 1, 1, tzinfo=dt.timezone.utc)
for z in zones:
    tz = ZoneInfo(z)
    for hours in range(0, 24 * 365 * 4, 37):  # every 37 h over 4 years hits all hours/transitions
        t = start + dt.timedelta(hours=hours, minutes=(hours * 7) % 60)
        offsets.append((z, int(t.timestamp()), int(t.astimezone(tz).utcoffset().total_seconds())))
    for day in range(0, 365 * 3, 5):  # wall clock -> UTC (fold=0, like Python's default)
        d = dt.date(2026, 1, 1) + dt.timedelta(days=day)
        for hh, mm in ((0, 0), (1, 30), (2, 30), (3, 0), (12, 0), (23, 45)):
            local = dt.datetime(d.year, d.month, d.day, hh, mm, tzinfo=tz)
            conversions.append((z, d.year, d.month, d.day, hh, mm, int(local.timestamp())))

out = os.path.join(ROOT, "tests/host/fixtures/tz_fixture.h")
with open(out, "w") as f:
    f.write("// Generated by tools/gen_tz_fixture.py from Python zoneinfo. Do not edit.\n#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct { const char *zone; int64_t utc; int offset; } tz_offset_case_t;\n")
    f.write("typedef struct { const char *zone; int y, m, d, hh, mm; int64_t utc; } tz_local_case_t;\n\n")
    f.write("static const tz_offset_case_t TZ_OFFSET_CASES[] = {\n")
    f.writelines(f'    {{"{z}", {u}, {o}}},\n' for z, u, o in offsets)
    f.write("};\nstatic const tz_local_case_t TZ_LOCAL_CASES[] = {\n")
    f.writelines(f'    {{"{z}", {y}, {m}, {d}, {hh}, {mm}, {u}}},\n' for z, y, m, d, hh, mm, u in conversions)
    f.write("};\n")
print(f"wrote {len(offsets)} offset and {len(conversions)} conversion cases for {len(zones)} zones")
