#!/usr/bin/env python3
"""Generate tests/host/fixtures/ical_fixture.h: what the Raspberry Pi version shows for the sample
feeds in tests/host/ical/, computed by its own code (homeplanner.external.calendar_events, built on
recurring_ical_events). The panel's C expander must produce the same occurrences.

Runs with the Pi repo's virtualenv:
    ../homeplanner/.venv/bin/python tools/gen_ical_fixture.py
"""
import os
import sys
from datetime import date
from zoneinfo import ZoneInfo

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
PI_REPO = os.environ.get("HOMEPLANNER_PI", os.path.join(ROOT, "..", "homeplanner"))
sys.path.insert(0, os.path.join(PI_REPO, "src"))

from homeplanner.external import ExternalCalendar, calendar_events, load_calendar  # noqa: E402

FEEDS = ["school.ics", "weekly_tz.ics", "rules.ics", "outlook.ics"]
RUNS = [  # (panel timezone, first day, days)
    ("America/Los_Angeles", date(2026, 8, 30), 196),
    ("Europe/Amsterdam", date(2026, 9, 6), 126),
    ("Australia/Sydney", date(2026, 9, 27), 42),
]
POSIX = dict(
    line.split('"')[1::2]
    for line in open(os.path.join(ROOT, "components/tz/tz_table.c"))
    if line.startswith('    {"')
)


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


cases = []
for feed in FEEDS:
    cal = load_calendar(open(os.path.join(ROOT, "tests/host/ical", feed), "rb").read())
    ext = ExternalCalendar(id="t", name="Test", url="https://example.com", color_id="1")
    for zone, start, days in RUNS:
        tz = ZoneInfo(zone)
        events = calendar_events(cal, ext, tz, start, date.fromordinal(start.toordinal() + days))
        rows = sorted((int(e.start.timestamp()), int(e.end.timestamp()), e.all_day, e.title, e.location or "")
                      for e in events)
        cases.append((feed, zone, start, days, rows))

out = os.path.join(ROOT, "tests/host/fixtures/ical_fixture.h")
with open(out, "w") as f:
    f.write("// Generated by tools/gen_ical_fixture.py from the Pi version's calendar_events(). Do not edit.\n")
    f.write("#pragma once\n#include <stdbool.h>\n#include <stdint.h>\n\n")
    f.write("typedef struct { int64_t start, end; bool all_day; const char *title, *location; } ical_expected_t;\n")
    f.write("typedef struct { const char *feed, *zone, *posix; int y, m, d, days; int count;"
            " const ical_expected_t *rows; } ical_case_t;\n\n")
    for i, (_, _, _, _, rows) in enumerate(cases):
        f.write(f"static const ical_expected_t ICAL_ROWS_{i}[] = {{\n")
        for s, e, a, t, loc in rows:
            f.write(f"    {{{s}, {e}, {'true' if a else 'false'}, {c_str(t)}, {c_str(loc)}}},\n")
        f.write("    {0, 0, false, NULL, NULL},\n};\n")
    f.write("\nstatic const ical_case_t ICAL_CASES[] = {\n")
    for i, (feed, zone, start, days, rows) in enumerate(cases):
        f.write(f'    {{"{feed}", "{zone}", {c_str(POSIX[zone])}, {start.year}, {start.month}, {start.day}, '
                f"{days}, {len(rows)}, ICAL_ROWS_{i}}},\n")
    f.write("};\n")
print(f"wrote {len(cases)} cases, {sum(len(c[4]) for c in cases)} occurrences")
